{% set version = "0.99-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proftools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/proftools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/proftools/proftools_{{ version }}.tar.gz
  sha256: e034eb1531af54013143da3e15229e1d4c2260f8eb79c93846014db3bdefb724

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('proftools')"           # [not win]
    - "\"%R%\" -e \"library('proftools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=proftools
  license: GPL-2.0-or-later
  summary: Tools for examining Rprof profile output.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: proftools
# Title: Profile Output Processing Tools for R
# Version: 0.99-2
# Author: Luke Tierney and Riad Jarjour
# Description: Tools for examining Rprof profile output.
# Maintainer: Luke Tierney <luke-tierney@uiowa.edu>
# Suggests: graph,Rgraphviz,boot,knitr
# VignetteBuilder: knitr
# License: GPL
# ByteCompile: yes
# NeedsCompilation: no
# Packaged: 2016-01-13 13:00:16 UTC; luke
# Repository: CRAN
# Date/Publication: 2016-01-13 14:53:18
