appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: lM2eqj5CJAU8A1yoMpNBYXOG9ycaPke5/X7jMijMM8aPcMegTNYJQ21muCcLA7uH5T8Fx59cTihSXjJVnOmqqyg/FKzLyzZZvxuz1IJ8K8IK9JXTaFAuBl6uVOaThB8SrIDQd3XsIzGDxt9lFMPlQ+DFkLifyhfzZ/EqrWnWxjqy48T6+tHmaC2AMHj95ygHvUJwpUk7+H5ldN0cUUiGKkifZLkddw5p14PSpQQBhC7Ok2i47cYYOm7HqhmeGvZFU4PXWEu1zN/2geIGm6BuZOW/Vd0Xv7VvjLGXavDuAhDk9HfVrqfVDscqgpfYCKG4XZtlHLLvZTB5oy76f0Qk8sdS2pAXfHpiZQHJXwrmqQneSbtC6Qpt/B2VIyKhWhvjbcSf6ZjlEegHH0MYFH2fsKi0oiMqjjINnmxkd1w3wv9qoKhyVvkaAvWL7w4SgkrXiHG+9a+j3axizgf45AqE+kLe7UZuedQl8/ODW8iVu49RYtc9su7anR2r+A584fv2t7uvMUXyyrKIhPn3dqtRO2zueV0lT+TEJhRmXvxiIaj9EW8e1aUwYahMlv2907mUUchw4bAA/f2E09aIL1sx+oVtLSCpRHCqj8NURzrhn3J5l3ig8w7FResZ5ChA6VKsWVAd+pTb6pZ966B44d3iJmnh2Z/rwKXjsUfamAu3q2o=
